contact_links:
  - name: Ask a question
    url: https://github.com/nikitabobko/AeroSpace/discussions/categories/questions-and-answers
    about: Please ask and answer questions here.
  - name: Feature request/idea
    url: https://github.com/nikitabobko/AeroSpace/discussions/categories/feature-ideas
    about: All not yet well-defined feature requests must be firstly brainstormed in "feature ideas".
