# For all possible keys and modifiers see: https://github.com/nikitabobko/AeroSpace/blob/main/src/config/keysMap.swift

# todo review defaults

after-startup-command = [] # You can use it to add command or commands that run after startup.
use-padding-for-nested-containers-with-the-same-orientation = true
auto-flatten-containers = true
# auto-different-orientation-for-nested-containers = true
# start-at-login = true
floating-windows-on-top = true
focus-wrapping = 'workspace'
main-layout = 'h_list' # todo change
DEBUG-all-windows-are-floating = false

[mode.main.binding]
alt-enter = 'exec_and_forget open /System/Applications/Utilities/Terminal.app'

alt-slash = 'layout h_list v_list'
alt-comma = 'layout h_accordion v_accordion'

# todo focus floating binding

# Focus window
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-backslash = 'close_all_windows_but_current'

# Move window

alt-shift-k = 'move_through up'
alt-shift-h = 'move_through left'
alt-shift-j = 'move_through down'
alt-shift-l = 'move_through right'

# Resize window
# alt-shift-minus  = 'resize shrink height 2 px'
# alt-shift-equal  = 'resize grow height 2 px'
# alt-shift-comma  = 'resize shrink width 2 px'
# alt-shift-period = 'resize grow width 2 px'

alt-0 = 'workspace 000'
alt-1 = 'workspace 111'
alt-2 = 'workspace 222'
alt-3 = 'workspace 333'
alt-4 = 'workspace 444'
alt-5 = 'workspace 555'
alt-6 = 'workspace 666'
alt-7 = 'workspace 777'
alt-8 = 'workspace 888'
alt-9 = 'workspace 999'
alt-a = 'workspace AAA'
alt-b = 'workspace BBB'
alt-c = 'workspace CCC'
alt-d = 'workspace DDD'
alt-e = 'workspace EEE'
alt-f = 'workspace FFF'
alt-g = 'workspace GGG'
alt-i = 'workspace III'
alt-m = 'workspace MMM'
alt-n = 'workspace NNN'
alt-o = 'workspace OOO'
alt-p = 'workspace PPP'
alt-q = 'workspace QQQ'
alt-r = 'workspace RRR'
alt-s = 'workspace SSS'
alt-t = 'workspace TTT'
alt-u = 'workspace UUU'
alt-v = 'workspace VVV'
alt-w = 'workspace WWW'
alt-x = 'workspace XXX'
alt-y = 'workspace YYY'
alt-z = 'workspace ZZZ'

alt-shift-semicolon = 'mode service'

alt-shift-0 = 'move_container_to_workspace 000'
alt-shift-1 = 'move_container_to_workspace 111'
alt-shift-2 = 'move_container_to_workspace 222'
alt-shift-3 = 'move_container_to_workspace 333'
alt-shift-4 = 'move_container_to_workspace 444'
alt-shift-5 = 'move_container_to_workspace 555'
alt-shift-6 = 'move_container_to_workspace 666'
alt-shift-7 = 'move_container_to_workspace 777'
alt-shift-8 = 'move_container_to_workspace 888'
alt-shift-9 = 'move_container_to_workspace 999'
alt-shift-a = 'move_container_to_workspace AAA'
alt-shift-b = 'move_container_to_workspace BBB'
alt-shift-c = 'move_container_to_workspace CCC'
alt-shift-d = 'move_container_to_workspace DDD'
alt-shift-e = 'move_container_to_workspace EEE'
alt-shift-f = 'move_container_to_workspace FFF'
alt-shift-g = 'move_container_to_workspace GGG'
alt-shift-i = 'move_container_to_workspace III'
alt-shift-m = 'move_container_to_workspace MMM'
alt-shift-n = 'move_container_to_workspace NNN'
alt-shift-o = 'move_container_to_workspace OOO'
alt-shift-p = 'move_container_to_workspace PPP'
alt-shift-q = 'move_container_to_workspace QQQ'
alt-shift-r = 'move_container_to_workspace RRR'
alt-shift-s = 'move_container_to_workspace SSS'
alt-shift-t = 'move_container_to_workspace TTT'
alt-shift-u = 'move_container_to_workspace UUU'
alt-shift-v = 'move_container_to_workspace VVV'
alt-shift-w = 'move_container_to_workspace WWW'
alt-shift-x = 'move_container_to_workspace XXX'
alt-shift-y = 'move_container_to_workspace YYY'
alt-shift-z = 'move_container_to_workspace ZZZ'

alt-tab = 'workspace_back_and_forth'

# alt-shift-slash.alt-shift-k = 'move_in up'
# alt-shift-slash.alt-shift-h = 'move_in left'
# alt-shift-slash.alt-shift-j = 'move_in down'
# alt-shift-slash.alt-shift-l = 'move_in right'

[mode.service.binding]
r = ['flatten_workspace_tree', 'mode main']
o = ['reload_config', 'mode main']
s = ['layout sticky', 'mode main']
f = ['layout floating', 'mode main']
k = 'focus parent'
j = 'focus child'
esc = 'mode main'
enter = 'mode main'
