# For all possible keys and modifiers see: https://github.com/nikitabobko/AeroSpace/blob/main/src/config/keysMap.swift

# todo review defaults

after-login-command = [] # You can use it to add command or commands that run after login to macOS user session.
after-startup-command = [] # You can use it to add command or commands that run after startup.
indent-for-nested-containers-with-the-same-orientation = 30
auto-flatten-containers = true
auto-opposite-orientation-for-nested-containers = true
start-at-login = false
floating-windows-on-top = true
main-layout = 'h_list' # todo change
DEBUG-all-windows-are-floating = false # todo drop
accordion-padding = 30 # todo dp?

[mode.main.binding]
alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

alt-slash = 'layout h_list v_list' # todo layout vs change-parent-container-kind
alt-comma = 'layout h_accordion v_accordion'

# todo focus floating binding

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move-through left'
alt-shift-j = 'move-through down'
alt-shift-k = 'move-through up'
alt-shift-l = 'move-through right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-0 = 'workspace 0'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-a = 'workspace A'
alt-b = 'workspace B'
alt-c = 'workspace C'
alt-d = 'workspace D'
alt-e = 'workspace E'
alt-f = 'workspace F'
alt-g = 'workspace G'
alt-i = 'workspace I'
alt-m = 'workspace M'
alt-n = 'workspace N'
alt-o = 'workspace O'
alt-p = 'workspace P'
alt-q = 'workspace Q'
alt-r = 'workspace R'
alt-s = 'workspace S'
alt-t = 'workspace T'
alt-u = 'workspace U'
alt-v = 'workspace V'
alt-w = 'workspace W'
alt-x = 'workspace X'
alt-y = 'workspace Y'
alt-z = 'workspace Z'

alt-shift-semicolon = 'mode service'
alt-shift-slash = 'mode move-in'

alt-shift-0 = 'move-container-to-workspace 0'
alt-shift-1 = 'move-container-to-workspace 1'
alt-shift-2 = 'move-container-to-workspace 2'
alt-shift-3 = 'move-container-to-workspace 3'
alt-shift-4 = 'move-container-to-workspace 4'
alt-shift-5 = 'move-container-to-workspace 5'
alt-shift-6 = 'move-container-to-workspace 6'
alt-shift-7 = 'move-container-to-workspace 7'
alt-shift-8 = 'move-container-to-workspace 8'
alt-shift-9 = 'move-container-to-workspace 9'
alt-shift-a = 'move-container-to-workspace A'
alt-shift-b = 'move-container-to-workspace B'
alt-shift-c = 'move-container-to-workspace C'
alt-shift-d = 'move-container-to-workspace D'
alt-shift-e = 'move-container-to-workspace E'
alt-shift-f = 'move-container-to-workspace F'
alt-shift-g = 'move-container-to-workspace G'
alt-shift-i = 'move-container-to-workspace I'
alt-shift-m = 'move-container-to-workspace M'
alt-shift-n = 'move-container-to-workspace N'
alt-shift-o = 'move-container-to-workspace O'
alt-shift-p = 'move-container-to-workspace P'
alt-shift-q = 'move-container-to-workspace Q'
alt-shift-r = 'move-container-to-workspace R'
alt-shift-s = 'move-container-to-workspace S'
alt-shift-t = 'move-container-to-workspace T'
alt-shift-u = 'move-container-to-workspace U'
alt-shift-v = 'move-container-to-workspace V'
alt-shift-w = 'move-container-to-workspace W'
alt-shift-x = 'move-container-to-workspace X'
alt-shift-y = 'move-container-to-workspace Y'
alt-shift-z = 'move-container-to-workspace Z'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-display next'

[mode.service.binding]
r = ['flatten-workspace-tree', 'mode main']
o = ['reload-config', 'mode main']
s = ['layout sticky', 'mode main']
f = ['layout floating', 'mode main']
backslash = ['close-all-windows-but-current', 'mode main']
esc = 'mode main'
enter = 'mode main'

[mode.move-in.binding]
alt-shift-h = ['move-in left', 'mode main']
alt-shift-j = ['move-in down', 'mode main']
alt-shift-k = ['move-in up', 'mode main']
alt-shift-l = ['move-in right', 'mode main']
esc = 'mode main'
enter = 'mode main'
