name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # every day at 00:00

jobs:
  build:
    name: Build
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: |
          brew install gsed
      - name: xcodegen
        uses: xavierLowmiller/xcodegen-action@1.1.2
      - name: Build
        run: |
          ./build-debug.sh
          ./check-uncommitted-files.sh
      - name: Test
        run: ./run-tests.sh
