name: Build

on:
  push:
    branches:
      - 'main'
      - 'bobko/**'
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # every day at 00:00

jobs:
  build:
    strategy:
      matrix:
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md
        os: [macos-13, macos-14]
    name: Build
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .deps
          key: ${{ matrix.os }}-${{ runner.arch }}-${{ hashFiles('script/install-dep.sh', 'Gemfile', '.bundle/config') }}
      - run: brew install bash fish xcbeautify
      - run: ./script/install-dep.sh --all
      - run: ./build-debug.sh
      - run: ./run-tests.sh
        # "-" means "Sign to run locally". There is no aerospace-codesign-certificate in GH Actions
        # build-release.sh takes too much time to complete in macos-13.
        # Running build-release.sh only in macos-14, cuts the build time twice in GH Actions.
      - name: ./build-release.sh on macos-14
        run: |
          sw_vers -productVersion
          if sw_vers -productVersion | grep -q "^14"; then
            ./build-release.sh --codesign-identity -
            ./install-from-sources.sh --dont-rebuild
          fi
