name: Build

on:
  push:
    branches:
      - 'main'
      - 'bobko/**'
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # every day at 00:00

jobs:
  build:
    name: Build
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: brew install xcodegen gsed asciidoctor
      - name: Check dirty files
        run: |
          ./generate.sh
          ./script/check-uncommitted-files.sh
      - name: Build Debug
        # "-" means "Sign to run locally". There is no aerospace-codesign-certificate in GH Actions
        run: ./build-debug.sh --codesign-identity -
      - name: Test
        run: ./run-tests.sh
      - name: Build Release
        run: ./build-release.sh --codesign-identity -
