name: Build

on:
  push:
    branches:
      - 'main'
      - 'bobko/**'
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # every day at 00:00

env:
  AEROSPACE_CODE_SIGN_IDENTITY: '-' # Sign to run locally

jobs:
  build:
    name: Build
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: brew install xcodegen gsed asciidoctor
      - name: Check dirty files
        run: |
          (export AEROSPACE_CODE_SIGN_IDENTITY=; ./generate.sh)
          ./script/check-uncommitted-files.sh
      - name: Build
        run: ./build-debug.sh
      - name: Test
        run: ./run-tests.sh
      - name: Build docs
        run: ./build-docs.sh
